# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 20, size=2)
print(r_1)

[6 9]


In [3]:
r_2 = np.random.randint(1, 20, size=(1, 2))
print(r_2)

[[14  5]]


In [4]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.0388997 ]
 [0.38367217]]


In [5]:
r_4 = np.random.randint(20, 100, size=(4, 5))
print(r_4)

[[45 40 26 91 28]
 [74 24 45 32 24]
 [37 67 20 52 86]
 [56 28 33 45 71]]


In [6]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.06990639 0.60625766 0.41533104 0.45165351 0.48549616]
 [0.59850559 0.38968158 0.53093528 0.2701343  0.55106015]
 [0.20741475 0.1779396  0.08454607 0.59313773 0.15259417]
 [0.56924133 0.89658861 0.42898286 0.71709007 0.98658446]]


## Genrating Random Choices from an Array

In [7]:
students = np.array(['Luis', 'Charles', 'Corey', 'Blake', 'Alexus', 'Alondra', 'Daniel', 'Victoria', 'Hana', 'Lorah', 'Sonia', 'Samia'])

In [10]:
call_on = np.random.choice(students)
print(call_on)

Hana


In [11]:
breakout_groups = np.random.choice(students, size =(3, 4))
print(breakout_groups)
# wouldn't work well for actual breakout groups — duplicates are allowed, so one student could show up in multiple spots

[['Lorah' 'Sonia' 'Lorah' 'Blake']
 ['Daniel' 'Charles' 'Corey' 'Lorah']
 ['Alexus' 'Lorah' 'Sonia' 'Charles']]


In [12]:
call_on_weighted = np.random.choice(students, size=5, p=[
    .30,
    .10,
    .10,
    .10,
    .10,
    .05,
    .05,
    .05,
    .05,
    .05,
    .05,
    .00
])
print(call_on_weighted)
# all p values must sum to 1.0
# Samia gets a 0.00 weight — excluded entirely
# Luis has the highest weight at 0.30

['Corey' 'Luis' 'Alexus' 'Lorah' 'Luis']


## Generating a Normal Distribution

In [14]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

In [16]:
print(bell_curve)
# loc is the mean — the center of the distribution = 10
# scale is the standard deviation — how wide the spread is = 5
# size sets the output shape: 4 rows, 5 columns

[[17.29749665  3.39842367 13.05718439  4.57135022  6.61957549]
 [ 8.88763426 16.00621824 13.28659339 10.83087355  6.17131843]
 [12.66048918 13.32872402 18.14632642 10.36506833 12.13790401]
 [ 8.46116671 14.43251729 10.97181372 11.47594868  5.51090903]]
