# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [4]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

In [5]:
print(r_4)

[[63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]
 [50 76 39 71 71]]


In [6]:
np.random.shuffle(r_4)
print(r_4)

[[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]]


shuffle reorders the rows randomly but leaves the values inside each row untouched. It changes the original array — no copy is made.

In [10]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[49 66 56 62 34]
 [50 76 39 71 71]
 [50 35 62 20 38]
 [63 41 79 43 62]]
[[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]]


shuffle is for in-place reordering when you don't need the original order anymore.
permutation gives you a fresh shuffled copy while leaving the original array intact.

## Mathematical Operations

In [11]:
print(f"r_1: {r_1}, shape: {r_1.shape}")
print(f"r_2: {r_2}, shape: {r_2.shape}")
result = np.add(r_1, r_2)
print(f"result: {result}, shape: {result.shape}")

r_1: [ 6 12], shape: (2,)
r_2: [[ 9 15]], shape: (1, 2)
result: [[15 27]], shape: (1, 2)


In [18]:
print(f"r_1: {r_1}, shape: {r_1.shape}")
print(f"r_3: {r_3}, shape: {r_3.shape}")
result2 = np.add(r_1, r_3)
print(f"result: {result2}, shape: {result2.shape}")

r_1: [ 6 12], shape: (2,)
r_3: [[0.2630867 ]
 [0.61323603]], shape: (2, 1)
result: [[ 6.2630867  12.2630867 ]
 [ 6.61323603 12.61323603]], shape: (2, 2)


In [19]:
print(f"r_2: {r_2}, shape: {r_2.shape}")
print(f"r_4: {r_4}, shape: {r_4.shape}")
result3 = np.add(r_2, r_4)
print(f"result: {result3}, shape: {result3.shape}")

r_2: [[ 9 15]], shape: (1, 2)
r_4: [[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]], shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [20]:
try:
    print(np.add(r_1, r_4))
except ValueError as e:
    print(f"r_1 + r_4 error: {e}")
# r_1 has shape (2,) — doesn't line up with r_4's (4,5)

try:
    print(np.add(r_2, r_4))
except ValueError as e:
    print(f"r_2 + r_4 error: {e}")

try:
    print(np.add(r_3, r_4))
except ValueError as e:
    print(f"r_3 + r_4 error: {e}")

r_1 + r_4 error: operands could not be broadcast together with shapes (2,) (4,5) 
r_2 + r_4 error: operands could not be broadcast together with shapes (1,2) (4,5) 
r_3 + r_4 error: operands could not be broadcast together with shapes (2,1) (4,5) 


In [23]:
print(np.add(np.array([1]), r_4))

print(np.add(np.array([[1]]), r_4))

print(np.add(np.array([1,1,1,1,1]), r_4))

try:
    print(np.add(np.array([[1], [1]]), r_4))
except ValueError as e:
    print(f"error: {e}")

[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
error: operands could not be broadcast together with shapes (2,1) (4,5) 


Broadcasting automatically expands smaller arrays to fit the shape of the larger one so the operation can run element-wise.

## Rounding

In [27]:
print(f"r_3 original: {r_3}")
print(f"trunc: {np.trunc(r_3)}")
print(f"fix: {np.fix(r_3)}")
print(f"floor: {np.floor(r_3)}")
print(f"ceil: {np.ceil(r_3)}")
print(f"round: {np.round(r_3, 2)}")

r_3 original: [[0.2630867 ]
 [0.61323603]]
trunc: [[0.]
 [0.]]
fix: [[0.]
 [0.]]
floor: [[0.]
 [0.]]
ceil: [[1.]
 [1.]]
round: [[0.26]
 [0.61]]


## Cumulative Operations

In [28]:
print(f"r_4:\n{r_4}")
print(f"\nSum of all values: {np.sum(r_4)}")
print(f"\nSum along axis=0 (by column) : \n{np.sum(r_4, axis=0)}")
print(f"\nSum along axis=1 (by row) : \n{np.sum(r_4, axis=1)}")
print(f"\nCumulative sum:\n{np.cumsum(r_4)}")
print(f"\nCumulative sum along axis=0:\n{np.cumsum(r_4, axis=0)}")

r_4:
[[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]]

Sum of all values: 1067

Sum along axis=0 (by column) : 
[212 218 236 196 205]

Sum along axis=1 (by row) : 
[307 288 205 267]

Cumulative sum:
[  50  126  165  236  307  370  411  490  533  595  645  680  742  762
  800  849  915  971 1033 1067]

Cumulative sum along axis=0:
[[ 50  76  39  71  71]
 [113 117 118 114 133]
 [163 152 180 134 171]
 [212 218 236 196 205]]


## Grocery Problem

In [32]:
# vegetables, fruits, snacks, beverages
bag1 = np.array([1, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print(f"Bag 1: {bag1}")
print(f"Bag 2: {bag2}")

#Total items per bag
totals = np.array([np.sum(bag1), np.sum(bag2)])
print(f"The first bag contains {totals[0]} items, and the second bag contains {totals[1]} items.")

#Total per category
category_totals = np.add(bag1, bag2)
print(f"There are {category_totals[0]} vegetables, {category_totals[1]} fruits, {category_totals[2]} boxes of snacks, and {category_totals[3]} beverages in the two grocey bags.")

Bag 1: [1 3 4 0]
Bag 2: [4 0 1 2]
The first bag contains 8 items, and the second bag contains 7 items.
There are 5 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocey bags.


## Teamwork

In [33]:
# Monday through friday
# Ben missed Monday, Carla missed Wednesday - use 0 for missed days
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])

# Compile into one array
all_knocks = np.array([ali, ben, carla])
print(all_knocks)

#Total per person and overall
per_person = np.sum(all_knocks, axis=1)
total = np.sum(all_knocks)
print(f"Ali knocked on {per_person[0]} doors, Ben knocked on {per_person[1]}, Carla knocked on {per_person[2]}.")
print(f"Total doors knocked: {total}")

# Rolling total of estimated votes (1 vote per 2 door knocks)
daily_totals = np.sum(all_knocks, axis=0)
rolling_votes = np.cumsum(daily_totals) * .5
print(f"Rolling estimated votes by day: {rolling_votes}")

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]
Ali knocked on 21 doors, Ben knocked on 17, Carla knocked on 16.
Total doors knocked: 54
Rolling estimated votes by day: [ 4.  11.5 17.  22.  27. ]
